# Config file for automatic testing at travis-ci.com
dist: focal

language: python
python:
  - 3.9
#  - 3.8
#  - 3.7
#  - 3.6
#  - 3.5

env:
  - POETRY_VERSION=1.1.4

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python
  - source "$HOME/.poetry/env"
#  - sudo apt update
#  - sudo apt install python3-bs4

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
   - pip install -U tox-travis
   - poetry install

# Command to run tests, e.g. python setup.py test
script:
   - tox
   - make test

after_success:
  # Send coverage to coveralls:
  - pip install coveralls
  - coveralls

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: CSRedRat
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: CSRedRat/topalias
#    python: 3.9

notifications:
  email:
    on_success: never
    on_failure: change
